server:
  port: 5000

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
    url: jdbc-secretsmanager:mysql://meetravel-prod.c9sm844qqnvz.us-east-1.rds.amazonaws.com:3306/${MEETRAVEL_DB_SCHEMA}
    username: rds!db-2901c5d4-8793-4698-85b1-0da7e3f42923
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    baseline-version: 1.0.0
    default-schema: ${MEETRAVEL_DB_SCHEMA}
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
    url: jdbc-secretsmanager:mysql://meetravel-prod.c9sm844qqnvz.us-east-1.rds.amazonaws.com:3306
    user: rds!db-2901c5d4-8793-4698-85b1-0da7e3f42923

rabbitmq:
  host: ${MEETRAVEL_RABBITMQ_HOST}
  username: ${MEETRAVEL_RABBITMQ_USERNAME}
  password: ${MEETRAVEL_RABBITMQ_PASSWORD}
  amqp:
    port: ${MEETRAVEL_RABBITMQ_AMQP_PORT}
    virtual-host: ${MEETRAVEL_RABBITMQ_AMQP_VIRTUAL_HOST}
  stomp:
    port: ${MEETRAVEL_RABBITMQ_STOMP_PORT}
