spring:
  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
    url: jdbc-secretsmanager:mysql://meetravel-prod.ccfns6hbmlbr.ap-northeast-2.rds.amazonaws.com:3306
    username: rds!db-2a35318f-5e5c-4a56-b959-2d2713126fd6
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    baseline-version: 1.0.0
    default-schema: ${MEETRAVEL_DB_SCHEMA}
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
    url: jdbc-secretsmanager:mysql://meetravel-prod.ccfns6hbmlbr.ap-northeast-2.rds.amazonaws.com:3306
    user: rds!db-2a35318f-5e5c-4a56-b959-2d2713126fd6

rabbitmq:
  host: ${MEETRAVEL_RABBITMQ_HOST}
  username: ${MEETRAVEL_RABBITMQ_USERNAME}
  password: ${MEETRAVEL_RABBITMQ_PASSWORD}
  amqp:
    port: ${MEETRAVEL_RABBITMQ_AMQP_PORT}
    virtual-host: ${MEETRAVEL_RABBITMQ_AMQP_VIRTUAL_HOST}
  stomp:
    port: ${MEETRAVEL_RABBITMQ_STOMP_PORT}
