spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MEETRAVEL_DB_LOCAL_URL}
    username: ${MEETRAVEL_DB_USERNAME}
    password: ${MEETRAVEL_DB_PASSWORD}

rabbitmq:
  relay:
    host: ${MEETRAVEL_RABBITMQ_RELAY_HOST}
    port: ${MEETRAVEL_RABBITMQ_RELAY_PORT}
