spring:
  application:
    name: meetravel
  profiles:
    default: local

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secretKey: ${JWT_SECRET_KEY}
  token:
    header: Authorization
    access:
      expiration: 1800000 # 30? (1000L(ms -> s) * 60L(s -> m) * 30L(m -> h))
    refresh:
      expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> ??) * 14(2?))

auth:
  kakao:
    auth-url: https://kauth.kakao.com
    grant_type: authorization_code
    client_id: ${KAKAO_CLIENT_ID} # Client Id
    client_secret: ${KAKAO_CLIENT_SECRET} # Client Secret ?
    redirect_uri: ${KAKAO_REDIRECTED_URI}
    content_type: application/x-www-form-urlencoded

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true

tour_api:
  service_key: ${SERVICE_KEY}

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    com.meetravel: DEBUG

---
spring:
  confing:
    activate:
      on-profile: "local"

---
spring:
  confing:
    activate:
      on-profile: "prod"
