spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    format-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${MEETRAVEL_DB_LOCAL_URL}
      username: ${MEETRAVEL_DB_USERNAME}
      password: ${MEETRAVEL_DB_PASSWORD}

