spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MEETRAVEL_DB_LOCAL_URL}/${MEETRAVEL_DB_SCHEMA}
    username: ${MEETRAVEL_DB_USERNAME}
    password: ${MEETRAVEL_DB_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    baseline-version: 1.0.0
    default-schema: ${MEETRAVEL_DB_SCHEMA}
    url: ${MEETRAVEL_DB_LOCAL_URL}
    user: ${MEETRAVEL_DB_USERNAME}
    password: ${MEETRAVEL_DB_PASSWORD}

rabbitmq:
  host: ${MEETRAVEL_RABBITMQ_HOST}
  username: ${MEETRAVEL_RABBITMQ_USERNAME}
  password: ${MEETRAVEL_RABBITMQ_PASSWORD}
  amqp:
    port: ${MEETRAVEL_RABBITMQ_AMQP_PORT}
    virtual-host: ${MEETRAVEL_RABBITMQ_AMQP_VIRTUAL_HOST}
  stomp:
    port: ${MEETRAVEL_RABBITMQ_STOMP_PORT}
