CREATE TABLE `meetravel`.`share_travel_place` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `TRAVEL_PLAN_ID` BIGINT NOT NULL,
    `TRAVEL_PLACE_ID` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;