CREATE TABLE `meetravel`.`travel_place` (
    `PLACE_ID` VARCHAR(50) NOT NULL,
    `PLACE_TYPE` VARCHAR(20) NOT NULL,
    `TITLE` VARCHAR (50) NOT NULL,
    `ADDR1` VARCHAR(255) NOT NULL,
    `ADDR2` VARCHAR(255) NULL,
    `IMAGE` VARCHAR(255) NULL,
    `CREATE_DTM` DATETIME NOT NULL,
    `CREATOR` VARCHAR(25) NULL,
    `UPDATE_DTM` DATETIME NOT NULL,
    `UPDATER` VARCHAR(25) NULL,
    PRIMARY KEY (`PLACE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `meetravel`.`travel_review` (
    `REVIEW_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `PLACE_ID` VARCHAR(50) NOT NULL,
    `PLACE_TYPE` VARCHAR(20) NOT NULL,
    `LIKE_CNT` INT NOT NULL,
    `CREATE_DTM` DATETIME NOT NULL,
    `CREATOR` VARCHAR(25) NULL,
    `UPDATE_DTM` DATETIME NOT NULL,
    `UPDATER` VARCHAR(25) NULL,
    PRIMARY KEY (`REVIEW_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
