CREATE TABLE `meetravel`.`roles` (
    `ROLE_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `ROLE` VARCHAR(5) NOT NULL,
    `ROLE_DESC` VARCHAR(3) NOT NULL,
    `CREATE_DTM` DATETIME NOT NULL,
    `CREATOR` VARCHAR(25) NULL,
    `UPDATE_DTM` DATETIME NOT NULL,
    `UPDATER` VARCHAR(25) NULL,
    PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `meetravel`.`roles` (`ROLE`, `ROLE_DESC`, `CREATE_DTM`, `CREATOR`, `UPDATE_DTM`, `UPDATER`) VALUES
('USER', '사용자', NOW(), NULL, NOW(), NULL),
('ADMIN', '관리자', NOW(), NULL, NOW(), NULL);

CREATE TABLE `meetravel`.`user` (
    `USER_ID` VARCHAR(25) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `NAME` VARCHAR(255) NOT NULL,
    `NICKNAME` VARCHAR(6) NOT NULL,
    `BIRTH_DATE` DATE NOT NULL,
    `GENDER` VARCHAR(2) NOT NULL,
    `PHONE_NUMBER` VARCHAR(13) NOT NULL,
    `PROFILE_IMAGE_URL` VARCHAR(255) NULL,
    `TRAVEL_COUNT` VARCHAR(10) NOT NULL,
    `SCHEDULE_TYPE` VARCHAR(4) NOT NULL,
    `PLANNING_TYPE` VARCHAR(5) NOT NULL,
    `MBTI` VARCHAR(4) NOT NULL,
    `HOBBY` VARCHAR(20) NULL,
    `INTRO` VARCHAR(20) NULL,
    `SOCIAL_TYPE` VARCHAR(5) NOT NULL,
    `CREATE_DTM` DATETIME NOT NULL,
    `CREATOR` VARCHAR(25) NULL,
    `UPDATE_DTM` DATETIME NOT NULL,
    `UPDATER` VARCHAR(25) NULL,
    PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `meetravel`.`user_roles` (
    `USER_ROLE_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` VARCHAR(25) NOT NULL,
    `ROLE_ID` BIGINT NOT NULL,
    `ROLE` VARCHAR(5) NULL,
    `CREATE_DTM` DATETIME NOT NULL,
    `CREATOR` VARCHAR(25) NULL,
    `UPDATE_DTM` DATETIME NOT NULL,
    `UPDATER` VARCHAR(25) NULL,
    PRIMARY KEY (`USER_ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;