CREATE TABLE `meetravel`.`travel_plan` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CHAT_ROOM_ID` BIGINT NOT NULL,
    `CREATE_DTM` DATETIME NOT NULL,
    `CREATOR` VARCHAR(25) NULL,
    `UPDATE_DTM` DATETIME NOT NULL,
    `UPDATER` VARCHAR(25) NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `meetravel`.`travel_plan_keyword` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `TRAVEL_PLAN_ID` BIGINT NOT NULL,
    `TRAVEL_KEYWORD` VARCHAR(4) NOT NULL,
    `CREATE_DTM` DATETIME NOT NULL,
    `CREATOR` VARCHAR(25) NULL,
    `UPDATE_DTM` DATETIME NOT NULL,
    `UPDATER` VARCHAR(25) NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `meetravel`.`daily_plan` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `TRAVEL_PLAN_ID` BIGINT NOT NULL,
    `PLAN_DATE` DATE NOT NULL,
    `MEET_PLACE` VARCHAR(50) NULL,
    `MEET_TIME` VARCHAR(50) NULL,
    `CREATE_DTM` DATETIME NOT NULL,
    `CREATOR` VARCHAR(25) NULL,
    `UPDATE_DTM` DATETIME NOT NULL,
    `UPDATER` VARCHAR(25) NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `meetravel`.`daily_travel_place` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `DAILY_PLAN_ID` BIGINT NOT NULL,
    `TRAVEL_PLACE_ID` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;