CREATE TABLE `meetravel`.`refresh_token` (
    `USER_ID` VARCHAR(25) NOT NULL,
    `TOKEN` VARCHAR(255) NOT NULL UNIQUE,
    `EXPIRY_DATE_TIME` DATETIME NOT NULL,
    PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;